version: "3"
services:
  gateway-service:
    container_name: gateway-service
    build: .
    ports:
      - "3000:3000"
    restart: always
    networks:  # Associate the service with a network
      - beauticket_backend

networks:  # Define networks at the top-level
  beauticket_backend: