version: "3"
services:
  gateway-service:
    container_name: gateway-service
    build: .
    ports:
      - "3000:3000"
    restart: always
    networks:  
      - default

networks:
  default:
    external:
      name: beauticket_backend